### ISSUE TITLE
Linstor-controller stucks on managing a bunch of nodes

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#136]
to reproduce:
```bash
for i in {1..250}; do linstor n c test$i 10.9.8.$i; done
linstor n l | awk '/(PLAIN)/ { print "linstor n i m -p 3367 --communication-type SSL " $2 " default" }' | sh -ex
```

**Comment by ghernadi** [comment]
Thanks for the report - this is a classic deadlock scenario. Will try to fix this. I will come back here when I have an update on this.

**Comment by ghernadi** [comment]
I guess I found the issue, fix should be included in next release. Feel free to reopen if the issue still occurs in `>1.6.2`

**Comment by kvaps** [comment]
@ghernadi doesn't it affect on https://github.com/LINBIT/linstor-server/issues/123?

**Comment by ghernadi** [comment]
I doubt. As you have shown yourself, somehow all your CPUs were quite busy, so I assume something didn't finish, maybe an endless-loop or something. (to be fully honest, I did not have too much time to look into this, especially as it seems to work with java 8)

The bug I just fixed for this issue 136 here was literally a deadlock, where two threads were *waiting* for each other :)

**Comment by kvaps** [comment]
OK, thank you for information!

**Comment by kvaps** [comment]
@ghernadi unfortunately I still have the deadlock on `v1.7.1`, you are having our database dump, try run:

```bash
linstor n l | awk '/(PLAIN)/ { print "linstor n i m -p 3367 --communication-type SSL " $2 " default" }' | sh -ex
```

Now it can handle more resources, but still have a chance to be freezes

**Comment by kvaps** [comment]
```
linstor n l | awk '/(SSL)/ { print "linstor n i m -p 3366 --communication-type Plain " $2 " default" }' | sh -ex
```

reverse side change passed without problems, probably this is another problem https://github.com/LINBIT/linstor-server/issues/141#issuecomment-632382208

**Comment by ghernadi** [comment]
> you are having our database dump, try run:

yes, I have the database dump, but I dont have your nodes :) I am almost sure that the bug is somewhere in the connection-establishing, which I cannot perform without having (or somehow faking) all of your nodes. 

I guess I will have to think about this a bit longer, or come up with a different approach...

**Comment by ghernadi** [comment]
Just to make sure: are we here really talking about a deadlock (i.e. linstor threads are waiting for each other) or could it still be (as you guessed earlier) related to #123 ? 

You should be able to check the difference by checking your CPU load while linstor hangs. High load would suggest #123, low CPU load should mean deadlock.

**Comment by kvaps** [comment]
Hi @ghernadi, when bug happens the CPU utilization was not so high like in #123,
But if I remember it correct, this is possible that one core was used for 100% the rest cores were always fully free.

Unfortunately I can't provide you more detailed information yet, I hope I will have time to reproduce this in a week

**Comment by rp-** [comment]
I assume this is the same as #141

**Comment by kvaps** [comment]
> I assume this is the same as #141

Exactly, closing as duplicated
