### ISSUE TITLE
Can't upgrade to 1.3.0 -->  1.4.0

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#98]
```
LINSTOR, Module Controller
Version:            1.4.0 (7e49d9935043ec8528406360acac188fdff9fafb)
Build time:         2020-01-14T13:49:26+00:00
Java Version:       11
Java VM:            Private Build, Version 11.0.5+10-post-Ubuntu-0ubuntu1.118.04
Operating system:   Linux, Version 4.15.18-12-pve
Environment:        amd64, 1 processors, 7756 MiB memory reserved for allocations
System components initialization in progress
16:25:22.862 [main] INFO  LINSTOR/Controller - SYSTEM - Log directory set to: '/logs'
16:25:22.916 [main] INFO  LINSTOR/Controller - SYSTEM - Linstor configuration file loaded from '/config/linstor.toml'.
16:25:22.917 [Main] INFO  LINSTOR/Controller - SYSTEM - Loading API classes started.
16:25:23.363 [Main] INFO  LINSTOR/Controller - SYSTEM - API classes loading finished: 445ms
16:25:23.363 [Main] INFO  LINSTOR/Controller - SYSTEM - Dependency injection started.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/linstor-server/lib/guice-4.2.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
16:25:24.859 [Main] INFO  LINSTOR/Controller - SYSTEM - Dependency injection finished: 1495ms
16:25:25.095 [Main] INFO  LINSTOR/Controller - SYSTEM - Initializing authentication subsystem
16:25:25.246 [Main] INFO  LINSTOR/Controller - SYSTEM - Initializing the database connection pool
16:25:25.559 [Main] INFO  org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 5.2.4 by Boxfuse
16:25:25.582 [Main] INFO  org.flywaydb.core.internal.database.DatabaseFactory - Database: jdbc:postgresql://linstor-db-stolon-proxy/linstor2 (PostgreSQL 10.5)
16:25:25.766 [Main] INFO  org.flywaydb.core.internal.command.DbValidate - Successfully validated 35 migrations (execution time 00:00.082s)
16:25:25.791 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Current version of schema "LINSTOR": 2019.11.12.01.01
16:25:25.791 [Main] WARN  org.flywaydb.core.internal.command.DbMigrate - outOfOrder mode is active. Migration of schema "LINSTOR" may not be reproducible.
16:25:25.792 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema "LINSTOR" to version 2019.11.21.01.01 - Unifies resources and snapshots
16:25:27.990 [Main] ERROR org.flywaydb.core.internal.command.DbMigrate - Migration of schema "LINSTOR" to version 2019.11.21.01.01 - Unifies resources and snapshots failed! Changes successfully rolled back.
16:25:28.261 [Main] ERROR LINSTOR/Controller - SYSTEM - SQL State  : 42703
Error Code : 0
Message    : The column name DRIVER_NAME was not found in this ResultSet.
 [Report number 5E1DEB72-00000-000000]
16:25:28.301 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutdown in progress
16:25:28.320 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutting down service instance 'DatabaseService' of type DatabaseService
16:25:28.337 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Waiting for service instance 'DatabaseService' to complete shutdown
16:25:28.338 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutting down service instance 'TaskScheduleService' of type TaskScheduleService
16:25:28.338 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Waiting for service instance 'TaskScheduleService' to complete shutdown
16:25:28.339 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutting down service instance 'TimerEventService' of type TimerEventService
16:25:28.339 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Waiting for service instance 'TimerEventService' to complete shutdown
16:25:28.339 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutdown complete
```

[ErrorReport-5E1DEB72-00000-000000.log](https://github.com/LINBIT/linstor-server/files/4060230/ErrorReport-5E1DEB72-00000-000000.log)

**Comment by Stibila** [comment]
We have similar problem, except we don't use PostgreSQL, but H2 database.

My syslog after trying to start Linstor Controller:

> Jan 15 13:08:42 linstor-controller Controller[12947]: LINSTOR, Module Controller
> Jan 15 13:08:42 linstor-controller Controller[12947]: Version:            1.4.0 (7e49d9935043ec8528406360acac188fdff9fafb)
> Jan 15 13:08:42 linstor-controller Controller[12947]: Build time:         2020-01-14T13:27:00+00:00
> Jan 15 13:08:42 linstor-controller Controller[12947]: Java Version:       11
> Jan 15 13:08:42 linstor-controller Controller[12947]: Java VM:            Private Build, Version 11.0.5+10-post-Ubuntu-0ubuntu1.118.04
> Jan 15 13:08:42 linstor-controller Controller[12947]: Operating system:   Linux, Version 4.15.0-70-generic
> Jan 15 13:08:42 linstor-controller Controller[12947]: Environment:        amd64, 2 processors, 239 MiB memory reserved for allocations
> Jan 15 13:08:42 linstor-controller Controller[12947]: System components initialization in progress
> Jan 15 13:08:43 linstor-controller Controller[12947]: 13:08:43.040 [main] INFO  LINSTOR/Controller - SYSTEM - Log directory set to: '/var/log/linstor-controller'
> Jan 15 13:08:43 linstor-controller Controller[12947]: 13:08:43.128 [main] INFO  LINSTOR/Controller - SYSTEM - Linstor configuration file loaded from '/etc/linstor/linstor.toml'.
> Jan 15 13:08:43 linstor-controller Controller[12947]: 13:08:43.129 [Main] INFO  LINSTOR/Controller - SYSTEM - Loading API classes started.
> Jan 15 13:08:43 linstor-controller Controller[12947]: 13:08:43.642 [Main] INFO  LINSTOR/Controller - SYSTEM - API classes loading finished: 513ms
> Jan 15 13:08:43 linstor-controller Controller[12947]: 13:08:43.643 [Main] INFO  LINSTOR/Controller - SYSTEM - Dependency injection started.
> Jan 15 13:08:43 linstor-controller Controller[12947]: WARNING: An illegal reflective access operation has occurred
> Jan 15 13:08:43 linstor-controller Controller[12947]: WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/linstor-server/lib/guice-4.2.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
> Jan 15 13:08:43 linstor-controller Controller[12947]: WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
> Jan 15 13:08:43 linstor-controller Controller[12947]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> Jan 15 13:08:43 linstor-controller Controller[12947]: WARNING: All illegal access operations will be denied in a future release
> Jan 15 13:08:45 linstor-controller Controller[12947]: 13:08:45.164 [Main] INFO  LINSTOR/Controller - SYSTEM - Dependency injection finished: 1521ms
> Jan 15 13:08:45 linstor-controller Controller[12947]: 13:08:45.518 [Main] INFO  LINSTOR/Controller - SYSTEM - Initializing authentication subsystem
> Jan 15 13:08:45 linstor-controller Controller[12947]: 13:08:45.723 [Main] INFO  LINSTOR/Controller - SYSTEM - Initializing the database connection pool
> Jan 15 13:08:46 linstor-controller Controller[12947]: 13:08:46.473 [Main] INFO  org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 5.2.4 by Boxfuse
> Jan 15 13:08:46 linstor-controller Controller[12947]: 13:08:46.485 [Main] INFO  org.flywaydb.core.internal.database.DatabaseFactory - Database: jdbc:h2:/var/lib/linstor/linstordb (H2 1.4)
> Jan 15 13:08:46 linstor-controller Controller[12947]: 13:08:46.681 [Main] ERROR LINSTOR/Controller - SYSTEM - Validate failed: Detected failed migration to version 2019.11.21.01.01 (Unifies resources and snapshots) [Report number 5E1F00CA-00000-000000]
> Jan 15 13:08:46 linstor-controller Controller[12947]: 13:08:46.704 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutdown in progress
> Jan 15 13:08:46 linstor-controller Controller[12947]: 13:08:46.729 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutting down service instance 'DatabaseService' of type DatabaseService
> Jan 15 13:08:46 linstor-controller Controller[12947]: 13:08:46.742 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Waiting for service instance 'DatabaseService' to complete shutdown
> Jan 15 13:08:46 linstor-controller Controller[12947]: 13:08:46.743 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutting down service instance 'TaskScheduleService' of type TaskScheduleService
> Jan 15 13:08:46 linstor-controller Controller[12947]: 13:08:46.743 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Waiting for service instance 'TaskScheduleService' to complete shutdown
> Jan 15 13:08:46 linstor-controller Controller[12947]: 13:08:46.744 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutting down service instance 'TimerEventService' of type TimerEventService
> Jan 15 13:08:46 linstor-controller Controller[12947]: 13:08:46.744 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Waiting for service instance 'TimerEventService' to complete shutdown
> Jan 15 13:08:46 linstor-controller Controller[12947]: 13:08:46.744 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutdown complete

Linstor log from /var/log/linstor-controller/ErrorReport-5E1F00CA-00000-000000.log

> ERROR REPORT 5E1F00CA-00000-000000
> 
> ============================================================
> 
> Application:                        LINBIT® LINSTOR
> Module:                             Controller
> Version:                            1.4.0
> Build ID:                           7e49d9935043ec8528406360acac188fdff9fafb
> Build time:                         2020-01-14T13:27:00+00:00
> Error time:                         2020-01-15 13:08:46
> Node:                               linstor-controller
> 
> ============================================================
> 
> Reported error:
> ===============
> 
> Category:                           RuntimeException
> Class name:                         FlywayException
> Class canonical name:               org.flywaydb.core.api.FlywayException
> Generated at:                       Method 'doValidate', Source file 'Flyway.java', Line #1482
> 
> Error message:                      Validate failed: Detected failed migration to version 2019.11.21.01.01 (Unifies resources and snapshots)
> 
> Call backtrace:
> 
>     Method                                   Native Class:Line number
>     doValidate                               N      org.flywaydb.core.Flyway:1482
>     access$100                               N      org.flywaydb.core.Flyway:85
>     execute                                  N      org.flywaydb.core.Flyway$1:1364
>     execute                                  N      org.flywaydb.core.Flyway$1:1356
>     execute                                  N      org.flywaydb.core.Flyway:1711
>     migrate                                  N      org.flywaydb.core.Flyway:1356
>     migrate                                  N      com.linbit.linstor.dbcp.DbConnectionPool:219
>     initialize                               N      com.linbit.linstor.dbcp.DbConnectionPoolInitializer:51
>     start                                    N      com.linbit.linstor.core.Controller:231
>     main                                     N      com.linbit.linstor.core.Controller:594
> 
> 
> END OF ERROR REPORT.

**Comment by ghernadi** [comment]
Hi,

@kvaps, thanks for the report, we found the issue, should be fixed in `v1.4.1`

@Stibila: the log says that flyway tried once to migrate, which failed for some reason. The log you are showing is only from the second or later run, basically only flyway saying "something happened in the past with this migration, please verify" and refuses to retry the migration.   
That means, I would like to see the original issue (the first attempt to migrate, i.e. the original cause of flyway marking that migration as failed)

If that reason is the same as kvaps showed (`The column name DRIVER_NAME was not found in this ResultSet.`) than please rollback to `v1.3.0` and wait for `v1.4.1`. Otherwise show me the error report

**Comment by Stibila** [comment]
Thanks, this log was from latest attempt to start service.
Here is original log:

> Jan 15 10:16:50 allitlinstor Controller[7953]: LINSTOR, Module Controller
> Jan 15 10:16:50 allitlinstor Controller[7953]: Version:            1.4.0 (7e49d9935043ec8528406360acac188fdff9fafb)
> Jan 15 10:16:50 allitlinstor Controller[7953]: Build time:         2020-01-14T13:27:00+00:00
> Jan 15 10:16:50 allitlinstor Controller[7953]: Java Version:       11
> Jan 15 10:16:50 allitlinstor Controller[7953]: Java VM:            Private Build, Version 11.0.5+10-post-Ubuntu-0ubuntu1.118.04
> Jan 15 10:16:50 allitlinstor Controller[7953]: Operating system:   Linux, Version 4.15.0-70-generic
> Jan 15 10:16:50 allitlinstor Controller[7953]: Environment:        amd64, 2 processors, 239 MiB memory reserved for allocations
> Jan 15 10:16:50 allitlinstor Controller[7953]: System components initialization in progress
> Jan 15 10:16:51 allitlinstor Controller[7953]: 10:16:51.669 [main] INFO  LINSTOR/Controller - SYSTEM - Log directory set to: '/var/log/linstor-controller'
> Jan 15 10:16:51 allitlinstor Controller[7953]: 10:16:51.784 [main] INFO  LINSTOR/Controller - SYSTEM - Linstor configuration file loaded from '/etc/linstor/linstor.toml'.
> Jan 15 10:16:51 allitlinstor Controller[7953]: 10:16:51.785 [Main] INFO  LINSTOR/Controller - SYSTEM - Loading API classes started.
> Jan 15 10:16:52 allitlinstor Controller[7953]: 10:16:52.363 [Main] INFO  LINSTOR/Controller - SYSTEM - API classes loading finished: 578ms
> Jan 15 10:16:52 allitlinstor Controller[7953]: 10:16:52.364 [Main] INFO  LINSTOR/Controller - SYSTEM - Dependency injection started.
> Jan 15 10:16:52 allitlinstor Controller[7953]: WARNING: An illegal reflective access operation has occurred
> Jan 15 10:16:52 allitlinstor Controller[7953]: WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/linstor-server/lib/guice-4.2.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
> Jan 15 10:16:52 allitlinstor Controller[7953]: WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
> Jan 15 10:16:52 allitlinstor Controller[7953]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> Jan 15 10:16:52 allitlinstor Controller[7953]: WARNING: All illegal access operations will be denied in a future release
> Jan 15 10:16:53 allitlinstor Controller[7953]: 10:16:53.888 [Main] INFO  LINSTOR/Controller - SYSTEM - Dependency injection finished: 1524ms
> Jan 15 10:16:54 allitlinstor Controller[7953]: 10:16:54.301 [Main] INFO  LINSTOR/Controller - SYSTEM - Initializing authentication subsystem
> Jan 15 10:16:54 allitlinstor Controller[7953]: 10:16:54.562 [Main] INFO  LINSTOR/Controller - SYSTEM - Initializing the database connection pool
> Jan 15 10:16:55 allitlinstor Controller[7953]: 10:16:55.533 [Main] INFO  org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 5.2.4 by Boxfuse
> Jan 15 10:16:55 allitlinstor Controller[7953]: 10:16:55.547 [Main] INFO  org.flywaydb.core.internal.database.DatabaseFactory - Database: jdbc:h2:/var/lib/linstor/linstordb (H2 1.4)
> Jan 15 10:16:55 allitlinstor Controller[7953]: 10:16:55.706 [Main] INFO  org.flywaydb.core.internal.command.DbValidate - Successfully validated 35 migrations (execution time 00:00.064s)
> Jan 15 10:16:55 allitlinstor Controller[7953]: 10:16:55.764 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Current version of schema "LINSTOR": 2019.12.04.01.01
> Jan 15 10:16:55 allitlinstor Controller[7953]: 10:16:55.765 [Main] WARN  org.flywaydb.core.internal.command.DbMigrate - outOfOrder mode is active. Migration of schema "LINSTOR" may not be reproducible.
> Jan 15 10:16:55 allitlinstor Controller[7953]: 10:16:55.766 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema "LINSTOR" to version 2019.11.04.01.01 - Adds new table for Writecache volumes [out of order]
> Jan 15 10:16:55 allitlinstor Controller[7953]: 10:16:55.902 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema "LINSTOR" to version 2019.11.12.01.01 - Split Resource.Flags.DISKLESS into DRBD_DISKLESS and NVME_INITIATOR [out of order]
> Jan 15 10:16:55 allitlinstor Controller[7953]: 10:16:55.956 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema "LINSTOR" to version 2019.11.21.01.01 - Unifies resources and snapshots [out of order]
> Jan 15 10:16:56 allitlinstor Controller[7953]: 10:16:56.447 [Main] ERROR org.flywaydb.core.internal.command.DbMigrate - Migration of schema "LINSTOR" to version 2019.11.21.01.01 - Unifies resources and snapshots [out of order] failed! Please restore backups and roll back database and code!
> Jan 15 10:16:56 allitlinstor Controller[7953]: 10:16:56.526 [Main] ERROR LINSTOR/Controller - SYSTEM - SQL State  : 23505
> Jan 15 10:16:56 allitlinstor Controller[7953]: Error Code : 23505
> Jan 15 10:16:56 allitlinstor Controller[7953]: Message    : Unique index or primary key violation: "UNQ_LDVD_MINOR_INDEX_9 ON LINSTOR.LAYER_DRBD_VOLUME_DEFINITIONS(VLM_MINOR_NR) VALUES (-1, 12)"; SQL statement:
> Jan 15 10:16:56 allitlinstor Controller[7953]: INSERT INTO LAYER_DRBD_VOLUME_DEFINITIONS(RESOURCE_NAME, RESOURCE_NAME_SUFFIX, SNAPSHOT_NAME, VLM_NR, VLM_MINOR_NR) VALUES (?, ?, ?, ?, ?) [23505-197]
> Jan 15 10:16:56 allitlinstor Controller[7953]:  [Report number 5E1ED882-00000-000000]
> Jan 15 10:16:56 allitlinstor Controller[7953]: 10:16:56.533 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutdown in progress
> Jan 15 10:16:56 allitlinstor Controller[7953]: 10:16:56.540 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutting down service instance 'DatabaseService' of type DatabaseService
> Jan 15 10:16:56 allitlinstor Controller[7953]: 10:16:56.547 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Waiting for service instance 'DatabaseService' to complete shutdown
> Jan 15 10:16:56 allitlinstor Controller[7953]: 10:16:56.548 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutting down service instance 'TaskScheduleService' of type TaskScheduleService
> Jan 15 10:16:56 allitlinstor Controller[7953]: 10:16:56.548 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Waiting for service instance 'TaskScheduleService' to complete shutdown
> Jan 15 10:16:56 allitlinstor Controller[7953]: 10:16:56.552 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutting down service instance 'TimerEventService' of type TimerEventService
> Jan 15 10:16:56 allitlinstor Controller[7953]: 10:16:56.553 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Waiting for service instance 'TimerEventService' to complete shutdown
> Jan 15 10:16:56 allitlinstor Controller[7953]: 10:16:56.554 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutdown complete

There seems to be different problem with unique index or primary key violation.

**Comment by ghernadi** [comment]
Please show me the ErrorReport `5E1ED882-00000-000000`

**Comment by Stibila** [comment]
Here

> ERROR REPORT 5E1ED882-00000-000000
> 
> ============================================================
> 
> Application:                        LINBIT® LINSTOR
> Module:                             Controller
> Version:                            1.4.0
> Build ID:                           7e49d9935043ec8528406360acac188fdff9fafb
> Build time:                         2020-01-14T13:27:00+00:00
> Error time:                         2020-01-15 10:16:56
> Node:                               linstor-controller
> 
> ============================================================
> 
> Reported error:
> ===============
> 
> Category:                           RuntimeException
> Class name:                         FlywayMigrateException
> Class canonical name:               org.flywaydb.core.internal.command.DbMigrate.FlywayMigrateException
> Generated at:                       Method 'doMigrateGroup', Source file 'DbMigrate.java', Line #373
> 
> Error message:                      SQL State  : 23505
> Error Code : 23505
> Message    : Unique index or primary key violation: "UNQ_LDVD_MINOR_INDEX_9 ON LINSTOR.LAYER_DRBD_VOLUME_DEFINITIONS(VLM_MINOR_NR) VALUES (-1, 12)"; SQL statement:
> INSERT INTO LAYER_DRBD_VOLUME_DEFINITIONS(RESOURCE_NAME, RESOURCE_NAME_SUFFIX, SNAPSHOT_NAME, VLM_NR, VLM_MINOR_NR) VALUES (?, ?, ?, ?, ?) [23505-197]
> 
> 
> Call backtrace:
> 
>     Method                                   Native Class:Line number
>     doMigrateGroup                           N      org.flywaydb.core.internal.command.DbMigrate:373
>     access$200                               N      org.flywaydb.core.internal.command.DbMigrate:54
>     call                                     N      org.flywaydb.core.internal.command.DbMigrate$3:284
>     execute                                  N      org.flywaydb.core.internal.jdbc.TransactionTemplate:74
>     applyMigrations                          N      org.flywaydb.core.internal.command.DbMigrate:281
>     migrateGroup                             N      org.flywaydb.core.internal.command.DbMigrate:246
>     access$100                               N      org.flywaydb.core.internal.command.DbMigrate:54
>     call                                     N      org.flywaydb.core.internal.command.DbMigrate$2:164
>     call                                     N      org.flywaydb.core.internal.command.DbMigrate$2:161
>     call                                     N      org.flywaydb.core.internal.database.base.Connection$1:147
>     execute                                  N      org.flywaydb.core.internal.jdbc.TransactionTemplate:74
>     lock                                     N      org.flywaydb.core.internal.database.base.Connection:143
>     lock                                     N      org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory:155
>     migrateAll                               N      org.flywaydb.core.internal.command.DbMigrate:161
>     migrate                                  N      org.flywaydb.core.internal.command.DbMigrate:139
>     execute                                  N      org.flywaydb.core.Flyway$1:1395
>     execute                                  N      org.flywaydb.core.Flyway$1:1356
>     execute                                  N      org.flywaydb.core.Flyway:1711
>     migrate                                  N      org.flywaydb.core.Flyway:1356
>     migrate                                  N      com.linbit.linstor.dbcp.DbConnectionPool:219
>     initialize                               N      com.linbit.linstor.dbcp.DbConnectionPoolInitializer:51
>     start                                    N      com.linbit.linstor.core.Controller:231
>     main                                     N      com.linbit.linstor.core.Controller:594
> 
> Caused by:
> ==========
> 
> Category:                           Exception
> Class name:                         JdbcSQLException
> Class canonical name:               org.h2.jdbc.JdbcSQLException
> Generated at:                       Method 'getJdbcSQLException', Source file 'DbException.java', Line #357
> 
> Error message:                      Unique index or primary key violation: "UNQ_LDVD_MINOR_INDEX_9 ON LINSTOR.LAYER_DRBD_VOLUME_DEFINITIONS(VLM_MINOR_NR) VALUES (-1, 12)"; SQL statement:
> INSERT INTO LAYER_DRBD_VOLUME_DEFINITIONS(RESOURCE_NAME, RESOURCE_NAME_SUFFIX, SNAPSHOT_NAME, VLM_NR, VLM_MINOR_NR) VALUES (?, ?, ?, ?, ?) [23505-197]
> 
> Call backtrace:
> 
>     Method                                   Native Class:Line number
>     getJdbcSQLException                      N      org.h2.message.DbException:357
>     get                                      N      org.h2.message.DbException:179
>     get                                      N      org.h2.message.DbException:155
>     getDuplicateKeyException                 N      org.h2.index.BaseIndex:101
>     requireUnique                            N      org.h2.mvstore.db.MVSecondaryIndex:236
>     add                                      N      org.h2.mvstore.db.MVSecondaryIndex:202
>     addRow                                   N      org.h2.mvstore.db.MVTable:732
>     insertRows                               N      org.h2.command.dml.Insert:182
>     update                                   N      org.h2.command.dml.Insert:134
>     update                                   N      org.h2.command.CommandContainer:102
>     executeUpdate                            N      org.h2.command.Command:261
>     executeUpdateInternal                    N      org.h2.jdbc.JdbcPreparedStatement:199
>     executeUpdate                            N      org.h2.jdbc.JdbcPreparedStatement:153
>     executeUpdate                            N      org.apache.commons.dbcp2.DelegatingPreparedStatement:136
>     executeUpdate                            N      org.apache.commons.dbcp2.DelegatingPreparedStatement:136
>     createLayerDrbdVlmDfnEntry               N      com.linbit.linstor.dbcp.migration.Migration_2019_11_21_UnifyResourceAndSnapshot:1053
>     createLayerDataForSnapshots              N      com.linbit.linstor.dbcp.migration.Migration_2019_11_21_UnifyResourceAndSnapshot:981
>     migrate                                  N      com.linbit.linstor.dbcp.migration.Migration_2019_11_21_UnifyResourceAndSnapshot:251
>     migrate                                  N      com.linbit.linstor.dbcp.migration.LinstorMigration:66
>     execute                                  N      org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor:48
>     doMigrateGroup                           N      org.flywaydb.core.internal.command.DbMigrate:367
>     access$200                               N      org.flywaydb.core.internal.command.DbMigrate:54
>     call                                     N      org.flywaydb.core.internal.command.DbMigrate$3:284
>     execute                                  N      org.flywaydb.core.internal.jdbc.TransactionTemplate:74
>     applyMigrations                          N      org.flywaydb.core.internal.command.DbMigrate:281
>     migrateGroup                             N      org.flywaydb.core.internal.command.DbMigrate:246
>     access$100                               N      org.flywaydb.core.internal.command.DbMigrate:54
>     call                                     N      org.flywaydb.core.internal.command.DbMigrate$2:164
>     call                                     N      org.flywaydb.core.internal.command.DbMigrate$2:161
>     call                                     N      org.flywaydb.core.internal.database.base.Connection$1:147
>     execute                                  N      org.flywaydb.core.internal.jdbc.TransactionTemplate:74
>     lock                                     N      org.flywaydb.core.internal.database.base.Connection:143
>     lock                                     N      org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory:155
>     migrateAll                               N      org.flywaydb.core.internal.command.DbMigrate:161
>     migrate                                  N      org.flywaydb.core.internal.command.DbMigrate:139
>     execute                                  N      org.flywaydb.core.Flyway$1:1395
>     execute                                  N      org.flywaydb.core.Flyway$1:1356
>     execute                                  N      org.flywaydb.core.Flyway:1711
>     migrate                                  N      org.flywaydb.core.Flyway:1356
>     migrate                                  N      com.linbit.linstor.dbcp.DbConnectionPool:219
>     initialize                               N      com.linbit.linstor.dbcp.DbConnectionPoolInitializer:51
>     start                                    N      com.linbit.linstor.core.Controller:231
>     main                                     N      com.linbit.linstor.core.Controller:594
> 
> 
> END OF ERROR REPORT.
>

**Comment by ghernadi** [comment]
Thanks, bug found and fixed.

I will keep this issue open until `v1.4.1` is released and verified that your issue is fixed.

**Comment by Stibila** [comment]
Do I need to downgrade/restore backup, or can I just wait for release? I already have upgraded satellites, so waiting a few days is more acceptable at this point. Another thing, is there an ETA for release?
And thanks a lot for your hard work ;)

**Comment by ghernadi** [comment]
You will at least need to restore database from the backup, as linstor currently has no mechanism to "repair" a failed flyway migration.  
You can leave your satellites upgraded as this issue only affects the controller, but you will also have to upgrade your satellites once `v1.4.1` is released.

Regarding the ETA, we are trying to make the release this week.

**Comment by kvaps** [comment]
Hi @ghernadi problem from https://github.com/LINBIT/linstor-server/issues/98#issue-549678488 is gone, but still not possible to upgrade, I've reported new issue https://github.com/LINBIT/linstor-server/issues/100

**Comment by kvaps** [comment]
This problem is solved for me, @Stibila culd I close the issue?

**Comment by Stibila** [comment]
It's solved for me as well, you can close it. Thanks.
